class BotResponseConstants:
    """
        Класс, содержащий в себе строковые константы, которые представляют собой ответ пользователю
      """
    sorry_response = 'Извините, но бот не смог подобрать выгодный вклад.'
    push_start_response = 'Нажми /start'
    not_understand_response = 'Я тебя не понимаю, нажми /start'
    welcome_response1 = 'Я умный бот, который поможет тебе разобраться с правильным вложением твоих денег!'
    welcome_response2 = 'С моей помощью ты сможешь выбрать один из следующих банков: Альфа, втб и тд потом заполним'
    input_sum_response = 'Введи сумму вклада'
    input_sum_response_again = 'Введи сумму повторно'
    good_and_choose_term ='Класс! Теперь давай выберем срок '
    digits_please_response = 'Цифрами, пожалуйста'
    user_name = 'Пользователь'
    goodbye_response = 'До новых сообщений!'
    term = 'Срок'
    sum = 'Сумма: '
    name = 'Имя: '
    choose_term = 'Выбрать срок'
    miss = 'Пропустить'
    want_to_specified_term = 'Давай приступим!\nДля начала скажи, ты хотел бы указать срок?'
    want_to_make_deposit_on = 'Ты хочешь оформить свой вклад на: '
    want_to_make_deposit_on_sum = 'Ты хочешь оформить вклад на сумму: '
    look_at_options = 'Класс! Вот, посмотри подобранные мной варианты: '
    yes = 'Да'
    no = 'Нет'
    your_term = 'Твой срок: '
    month = ' мес.'
    hello = 'Привет, '

